### PR TITLE
Add robust stability example

### PR DESCRIPTION
**Pull request by haudren**
This PR adds a new example to the `contact_stability` family. It illustrates how to compute a robust static stability polyhedron recursively: the display updates at each iteration until `max_iter` is reached.

Let me know what you think !

### CODE REVIEW

**Comment by stephane-caron** [comment]
Works for me, merged!

One  small comment: `self.polyhedron = stab.StabilityPolygon(...)` looks weird. If it returns a polyhedron, your function should be name accordingly.

As to what the polytope represents, I wonder what is your robustness criterion here:
- The `radius` parameter seems to be a simple geometric condition `|com - origin| < radius` (here `origin` will be the world origin `[0 0 0]`, right? maybe you want to specify a point linked with contact locations here)
- Is it `force_lim`, and what does its default value of 1 mean physically?
- Or is it `robust_sphere`, and in that case what is its unit and what does it mean physically?

**Comment by haudren** [comment]
Your two comments are actually linked: `StabilityPolygon` was first written as a "gigaclass" that could do any of the four combinations of robust / non-robust + 2D / 3D. To specify the robustness criteria, you have to write stuff to `polyhedron.gravity_envelope`, which is unintuitive at best :disappointed:  I have to find a better way to specify things without duplicating code.

For the things you specify:
- `radius` is indeed `|| com - origin || < radius`
- `force_lim` is a constraint `| f_{x,y,z} | < force_lim m g`
- `robust_sphere` uses another constraint (Corollary 1. in the paper): instead of enforcing stability for `n` accelerations, enforce a stronger conic constraint.

I think that the main problem is that there is (for now) no real generic way to re-use constraints. If I get to re-writing that part, it would be nice to actually split those into different projection problems.

**Comment by stephane-caron** [comment]
OK thanks for this clarification :)

Then, my question for this example is: how can we change the residual radius (_r_ in Definition 1 of the paper) of the robustness criterion?

**Comment by haudren** [comment]
Basically definition 1 is the ideal case, and cannot be computed. You can either:
- Use an over restrictive approximation and set `robust_sphere`
- Use a discretized set of accelerations, `gravity_envelope`

There is a simple example of how you can modify `gravity_envelope`in `unilateral_example.py`. If you'd like, I can add it to the pymanoid example.

**Comment by stephane-caron** [comment]
Yes please, that'd be great :)

**Pull request merged**
